services:

  mysql:
    image: mysql:8.0
    container_name: alurafood-pagamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alurafood-pagamento
    ports:
      - "3306:3306"

  rabbitmq1:
    image: rabbitmq:3.12-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: secretcookie
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq
      - ./rabbitmq1/init.sh:/init.sh
    command: ["/bin/bash", "/init.sh"]
    networks:
      - rabbitmq

  rabbitmq2:
    image: rabbitmq:3.12-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: secretcookie
    depends_on:
      - rabbitmq1
    volumes:
      - rabbitmq2-data:/var/lib/rabbitmq
      - ./rabbitmq2/init.sh:/init.sh
    command: ["/bin/bash", "/init.sh"]
    networks:
      - rabbitmq

  rabbitmq3:
    image: rabbitmq:3.12-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: secretcookie
    depends_on:
      - rabbitmq1
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq
      - ./rabbitmq3/init.sh:/init.sh
    command: ["/bin/bash", "/init.sh"]
    networks:
      - rabbitmq

networks:
  rabbitmq:

volumes:
  rabbitmq1-data:
  rabbitmq2-data:
  rabbitmq3-data: